disabled_rules:
- trailing_whitespace
- cyclomatic_complexity
- identifier_name
- function_body_length
- type_body_length
opt_in_rules:
- empty_count
# - missing_docs
# - force_unwrapping

excluded:
  - LoginExample
  - SteviaTests
  - Playground
